# Generated by Django 4.1.5 on 2026-07-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sudoku', '0003_userinfo_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='grid_size',
            field=models.IntegerField(default=9),
        ),
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField()),
                ('best_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='Sudoku.userinfo')),
            ],
            options={
                'unique_together': {('user_info', 'grid_size')},
            },
        ),
    ]
